### ISSUE TITLE
TypeError: Cannot destructure property `siteName` of ‘undefined’ or ‘null’. and www.html-js.cn can't access

### ISSUE THREAD

**Issue by webnoise** [doramart/DoraCMS#103]
www.html-js.cn can't access

run DoraCMS with log below. I suggest provide initial mongoldb data at git folder, don't use another website html-js.cn for you user guide

DoraCMS$ npm run dev

> doracms@2.0.5 dev /Users/XXX/Workspace/web/DoraCMS
> npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server

> doracms@2.0.5 static /Users/XXX/Workspace/web/DoraCMS
> node ./build/copy

server started at localhost:8080
连接数据成功
babel-preset-env: `DEBUG` option

Using targets:
{
  “chrome”: “52”
}

Modules transform: false

Using plugins:
  transform-async-to-generator {“chrome”:”52”}
  syntax-trailing-function-commas {“chrome”:”52”}

 DONE  Compiled successfully in 18766ms                                                                                                                                                             09:19:59

 DONE  Compiled successfully in 19169ms                                                                                                                                                             09:20:00

webpack built 5e881075e9883ac6a844 in 19169ms
[vue-router] Duplicate named routes definition: { name: “index”, path: “/page/:current(\d+)?” }
[vue-router] Duplicate named routes definition: { name: “category”, path: “/:cate0/:cate1?___:typeId?/:current(\d+)?” }
“GET /api/systemConfig/getConfig?cache=true&apiSource=server” 200 29 “-“ “axios/0.16.2”
“GET /api/content/getSimpleListByParams?pageSize=10&isTop=1&model=simple&cache=true&apiSource=server” 200 98 “-“ “axios/0.16.2”
“GET /api/message/getList?pageSize=5&apiSource=server” 200 97 “-“ “axios/0.16.2”
“GET /api/content/getSimpleListByParams?model=simple&pageSize=10&path=%2F&sortby=clickNum&cache=true&apiSource=server” 200 98 “-“ “axios/0.16.2”
“GET /api/ads/getAll?apiSource=server” 200 83 “-“ “axios/0.16.2”
“GET /api/content/getList?model=normal&pageSize=10&path=%2F&cache=true&apiSource=server” 200 98 “-“ “axios/0.16.2”
“GET /api/contentCategory/getList?model=full&path=%2F&cache=true&apiSource=server” 200 85 “-“ “axios/0.16.2”
data pre-fetch: 73ms
[Vue warn]: Error in created hook: “TypeError: Cannot destructure property `siteName` of ‘undefined’ or ‘null’.”

found in

—> <FrontendIndex> at /Users/XXX/Workspace/web/DoraCMS/src/index/views/ArticleList.vue
       <Root>
error during render : /
TypeError: Cannot destructure property `siteName` of ‘undefined’ or ‘null’.
    at VueComponent.metaInfo [as $metaInfo] (server/server-bundle.js:3506:61)
    at VueComponent.created (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-meta/lib/vue-meta.js:1033:16)
    at callHook (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue/dist/vue.runtime.common.js:2872:21)
    at VueComponent.Vue._init (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue/dist/vue.runtime.common.js:4521:5)
    at new VueComponent (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue/dist/vue.runtime.common.js:4691:12)
    at createComponentInstanceForVnode (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7517:10)
    at renderComponentInner (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7702:40)
    at renderComponent (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7677:5)
    at renderNode (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7593:5)
    at renderComponentInner (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7713:3)
    at renderComponent (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7677:5)
    at renderNode (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7593:5)
    at renderComponentInner (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7713:3)
    at renderComponent (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7677:5)
    at RenderContext.renderNode (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7593:5)
    at RenderContext.next (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:2450:14)
    at cachedWrite (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:2310:9)
    at renderStringNode (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7776:5)
    at RenderContext.renderNode (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:7591:5)
    at RenderContext.next (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:2450:14)
    at RenderContext.next (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:2459:12)
    at RenderContext.cachedWrite [as write] (/Users/XXX/Workspace/web/DoraCMS/node_modules/vue-server-renderer/build.js:2310:9)
“GET /“ 500 - “-“ “Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38”

**Comment by doramart** [comment]
Have you import base data by mongodb ?
