### ISSUE TITLE
bash: mongorestore: 未找到命令..

### ISSUE THREAD

**Issue by kroawen** [doramart/DoraCMS#105]
已经装了MONGODB

**Comment by doramart** [comment]
你要在mongodb的bin目录下执行，或者把bin目录配置到环境变量中去

**Comment by kroawen** [comment]
感谢解答，安装完后正常，但是用搜索就不行了。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doracms@2.0.5 dev: `npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doracms@2.0.5 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by doramart** [comment]
错误日志不完成，麻烦提供全一点

**Comment by kroawen** [comment]
> doracms@2.0.5 dev /var/www/cms/cms/DoraCMS
> npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server


> doracms@2.0.5 static /var/www/cms/cms/DoraCMS
> node ./build/copy

server started at localhost:8081

/var/www/DoraCMS/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/var/www/cms/cms/DoraCMS/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:159:13)
    at Connection.<anonymous> (/var/www/cms/cms/DoraCMS/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:254:19)
    at Connection.emit (events.js:159:13)
    at Socket.<anonymous> (/var/www/cms/cms/DoraCMS/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:254:19)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doracms@2.0.5 dev: `npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doracms@2.0.5 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-15T12_03_22_359Z-debug.log

**Comment by doramart** [comment]
mongodb 没有启动，doracms 连接不上数据库
