### ISSUE TITLE
git clone项目到本地，跑不起来，报错如下，求助各位

### ISSUE THREAD

**Issue by frankwang0909** [doramart/DoraCMS#118]
开发环境：
Win10
Node 8.5.0,
MongoDB 3.2。

MongoDB 正常启动了。
数据包doracms2.zip也导入了。

完整日志如下：
```bash
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.3.0
3 info using node@v8.5.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle doracms@2.0.5~predev: doracms@2.0.5
6 info lifecycle doracms@2.0.5~dev: doracms@2.0.5
7 verbose lifecycle doracms@2.0.5~dev: unsafe-perm in lifecycle true
8 verbose lifecycle doracms@2.0.5~dev: PATH: C:\Users\frank\AppData\Roaming\nvm\v8.5.0\node_modules\npm\bin\node-gyp-bin;c:\Users\frank\Desktop\Vue\DoraCMS\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\frank\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Users\frank\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Go\bin;E:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\dotnet\;C:\Users\frank\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\frank\AppData\Local\Programs\Python\Python35\;C:\Ruby23-x64\bin;C:\Program Files (x86)\Microsoft VS Code\bin;F:\php;G:\softwares\hugo\bin;C:\Users\frank\AppData\Local\Microsoft\WindowsApps;C:\xampp\mysql\bin;C:\Program Files\MongoDB\Server\3.4\bin
9 verbose lifecycle doracms@2.0.5~dev: CWD: c:\Users\frank\Desktop\Vue\DoraCMS
10 silly lifecycle doracms@2.0.5~dev: Args: [ '/d /s /c',
10 silly lifecycle   'npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server' ]
11 silly lifecycle doracms@2.0.5~dev: Returned: code: 1  signal: null
12 info lifecycle doracms@2.0.5~dev: Failed to exec dev script
13 verbose stack Error: doracms@2.0.5 dev: `npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\frank\AppData\Roaming\nvm\v8.5.0\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\frank\AppData\Roaming\nvm\v8.5.0\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid doracms@2.0.5
15 verbose cwd c:\Users\frank\Desktop\Vue\DoraCMS
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v8.5.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error doracms@2.0.5 dev: `npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
22 error Exit status 1
23 error Failed at the doracms@2.0.5 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by doramart** [comment]
没装依赖吧？

**Comment by sunceenjoy** [comment]
我也跑不起来，--> <FrontendIndex> at /Users/gsum/Documents/nodejs/DoraCMS/src/index/views/ArticleList.vue
       <Root>
error during render : /
TypeError: Cannot destructure property `siteName` of 'undefined' or 'null'.
    at VueComponent.metaInfo [as $metaInfo] (server/server-bundle.js:3506:61)


另外 部分测试数据库host写死在:./DoraCMS/server/lib/models/index.js?

**Comment by tbfungeek** [comment]
@frankwang0909  你的起来了吗

**Comment by deepcc** [comment]
数据库ok，打包报错
ERROR in ./~/.npminstall/babel-runtime/6.26.0/babel-runtime/core-js/promise.js
Module not found: Error: Can't resolve 'core-js/library/fn/promise' in 

--------------------------------------------
cnpm i，有问题，
换npm i 就好了，淘宝的镜像有问题

**Comment by frankwang0909** [comment]
@doramart  安装了依赖，数据库连接也正常。

**Comment by frankwang0909** [comment]
@deepcc  我用的就是npm，压根没用 淘宝的镜像。
@tbfungeek 没呢。你呢？

**Comment by doramart** [comment]
@frankwang0909 服务器的环境变量设置了吗？

**Comment by frankwang0909** [comment]
@doramart 不知道在哪里设置？

**Comment by frankwang0909** [comment]
@tbfungeek 项目可以正常启动了。

项目跑不起来有可能是以下原因：

#### 1. 没有正确安装所有依赖的包

开发工具（VS code）下的`终端`可能没有管理员权限，导致无法正确安装所有依赖的 npm 包。

解决方法：使用 Window 系统自动的命令行工具，执行 npm install。

#### 2. 默认 8080 端口 被占用：

命令行中输入以下命令可以查看 8080 端口被其他程序或者系统程序占用。
```bash
netstat -aon|findstr "8080" 
```

解决方法：如果被占用，可以修改端口，或者关闭占用该端口的程序。修改 `utils/setting.js` 的端口设置，比如改成 `serverPort: 8086`

**Comment by sunceenjoy** [comment]
补充一点，数据库要安装本机，都用默认参数。代码内部有硬编码，配置有地方根本不用。

**Comment by tbfungeek** [comment]
我的可以了
@doramart @frankwang0909 @sunceenjoy @deepcc @cobain 
我的是由于下面原因导致的，谢谢各位：

1. 没有正确安装所有依赖的包
开发工具（VS code）下的终端可能没有管理员权限，导致无法正确安装所有依赖的 npm 包。
解决方法：使用 Window 系统自动的命令行工具，执行 npm install。
