### ISSUE TITLE
向项目中添加一个页面 /src/index/views/xxx.vue 文件 报错 

### ISSUE THREAD

**Issue by yushk** [doramart/DoraCMS#120]
环境Ubuntu
node：8.9.1
终端打出的log如下：

`
error during render : /home
TypeError: Cannot read property 'registrationNo' of undefined
    at Proxy.render (server/server-bundle.js:10410:509)
    at VueComponent.Vue._render (/home/pana/workspace/yushkCms/node_modules/vue/dist/vue.runtime.common.js:4435:22)
    at renderComponentInner (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7707:25)
    at renderComponentWithCache (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7695:3)
    at /home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7648:11
    at /home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2497:40
    at renderComponent (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7638:7)
    at RenderContext.renderNode (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7593:5)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2450:14)
    at cachedWrite (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2310:9)
    at renderStringNode (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7776:5)
    at RenderContext.renderNode (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7591:5)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2450:14)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2459:12)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2459:12)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2459:12)
    at RenderContext.cachedWrite [as write] (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2310:9)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2453:14)
    at cachedWrite (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2310:9)
    at renderStringNode (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7776:5)
    at RenderContext.renderNode (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:7591:5)
    at RenderContext.next (/home/pana/workspace/yushkCms/node_modules/vue-server-renderer/build.js:2450:14)
"GET /home" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/62.0.3202.62 Chrome/62.0.3202.62 Safari/537.36"`

**Comment by doramart** [comment]
这个是你添加的代码有问题，请仔细看下doracms的代码结构，目测footer.vue中的getSystemConfig没有取到数据，请确认是否导入了初始数据
