### ISSUE TITLE
loader/lib/selector.js?type=template&index=0!./src/index/components/TopRecoContents.vue Module build failed: SyntaxError: Unexpected token (8:32)

### ISSUE THREAD

**Issue by epubreader** [doramart/DoraCMS#123]
ERROR in ./~/vue-loader/lib/template-compiler?{"id":"data-v-054d5c6b","hasScoped":false}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/index/components/TopRecoContents.vue
Module build failed: SyntaxError: Unexpected token (8:32)
    at Parser.pp$4.raise (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:2610:13)
    at Parser.pp.unexpected (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:637:8)
    at Parser.pp$2.parseBindingAtom (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1602:10)
    at Parser.pp$2.parseMaybeDefault (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1640:23)
    at Parser.pp$2.parseBindingList (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1625:25)
    at Parser.pp$1.parseFunctionParams (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1189:22)
    at Parser.pp$1.parseFunction (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1176:8)
    at Parser.pp$3.parseExprAtom (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:2082:17)
    at Parser.parseExprAtom (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:4372:24)
    at Parser.pp$3.parseExprSubscripts (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1932:17)
    at Parser.pp$3.parseExprOps (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1832:19)
    at Parser.pp$3.parseExprList (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:2528:20)
    at Parser.pp$3.parseSubscripts (E:\nodejs\DoraCMS\node_modules\vue-template-es2015-compiler\buble.js:1983:29)
 @ ./src/index/components/TopRecoContents.vue 10:2-214
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index/views/ArticleList.vue
 @ ./src/index/views/ArticleList.vue
 @ ./src/index/router/create-route-client.js
 @ ./src/index/router/index.js
 @ ./src/app.js
 @ ./src/entry-client.js

**Comment by epubreader** [comment]
npm run dev 报错是什么原因

**Comment by doramart** [comment]
是否修改了代码？看看这个文件TopRecoContents.vue 里是否有语法错误？

**Comment by epubreader** [comment]
v-for="(item) in currentlist" 这句代码有问题， 去掉就好了， 怎么修改好呢？

**Comment by epubreader** [comment]
v-for="item in currentlist" 这样就正常了

**Comment by doramart** [comment]
是的，语法问题
