### ISSUE TITLE
不知道为什吗？window 编译报错

### ISSUE THREAD

**Issue by 374046604** [doramart/DoraCMS#131]

**Comment by 374046604** [comment]
---> <FrontendIndex> at D:\xampp\htdocs\myTest02\DoraCMS-2.0.5\src\index\views\ArticleList.vue
       <Root>
error during render : /
TypeError: Cannot match against 'undefined' or 'null'.
    at VueComponent.metaInfo [as $metaInfo] (server/server-bundle.js:3506:61)
    at getTitle (server/server-bundle.js:521:58)
    at VueComponent.created (server/server-bundle.js:527:22)
    at callHook (D:\xampp\htdocs\myTest02\DoraCMS-2.0.5\node_modules\_vue@2.5.16@vue\dist\vue.runtime.common.js:2919:21)
    at VueComponent.Vue._init (D:\xampp\htdocs\myTest02\DoraCMS-2.0.5\node_modules\_vue@2.5.16@vue\dist\vue.runtime.comm
on.js:4628:5)
    at new VueComponent (D:\xampp\htdocs\myTest02\DoraCMS-2.0.5\node_modules\_vue@2.5.16@vue\dist\vue.runtime.common.js:
4796:12)
    at createComponentInstanceForVnode (D:\xampp\htdocs\myTest02\DoraCMS-2.0.5\node_modules\_vue-server-renderer@2.5.16@
vue-server-renderer\build.js:7342:10)
    at renderComponentInner (D:\xampp\htdocs\myTest02\DoraCMS-2.0.5\node_modules\_vue-server-renderer@2.5.16@vue-server-
renderer\build.js:7516:40)

**Comment by doramart** [comment]
删掉依赖重新装（cnpm install）

**Comment by loaden** [comment]
或者翻墙。出错后删除node_modules目录再试。
