### ISSUE TITLE
npm start后报这样的错误信息

### ISSUE THREAD

**Issue by somebin** [doramart/DoraCMS#159]
╰─$ npm start

> doracms@2.1.0 start /Users/gzyj/Desktop/DoraCMS
> npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server

> doracms@2.1.0 static /Users/gzyj/Desktop/DoraCMS
> node ./build/copy

Redis状态开关： true
server started at localhost:8090
node_redis: Warning: Redis server does not require a password, but a password was supplied.
node_redis: Warning: Redis server does not require a password, but a password was supplied.
connect mongodb success
babel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": "52"
}

Modules transform: false

Using plugins:
  transform-async-to-generator {"chrome":"52"}
  syntax-trailing-function-commas {"chrome":"52"}

 DONE  Compiled successfully in 19235ms                                 16:35:03

webpack built aefc85b0f02dd6e29b50 in 19235ms
"GET /" 200 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
---error--- Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at ServerResponse.header (/Users/gzyj/Desktop/DoraCMS/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/gzyj/Desktop/DoraCMS/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/gzyj/Desktop/DoraCMS/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/Users/gzyj/Desktop/DoraCMS/node_modules/express/lib/response.js:158:21)
    at Content.getContents (/Users/gzyj/Desktop/DoraCMS/server/lib/controller/content.js:239:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by toughbell** [comment]
也是同样的问题,请指教

**Comment by lovemybb** [comment]
先初始化数据，是因为没有主题数据，导致程序报错 基础数据链接地址 https://www.html-js.cn/details/ryn2kSWqZ.html

**Comment by doramart** [comment]
对的
