### ISSUE TITLE
npm run dev 报错，redis connection fail

### ISSUE THREAD

**Issue by zhoudaxiaa** [doramart/DoraCMS#165]
Redis状态开关： true
[0] server started at localhost:8080
[0] connect mongodb success
[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[0]     at Object._errnoException (util.js:1022:11)
[0]     at _exceptionWithHostPort (util.js:1044:20)
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! doracms@2.1.0 devNodeServer: `cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the doracms@2.1.0 devNodeServer script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-10-16T05_07_09_951Z-debug.log

**Comment by laurensmartz** [comment]
同问

**Comment by CharlesLiuyx** [comment]
一模一样的错误，有人解决了吗？我的环境是`Ubuntu1 16.04`

**Comment by doramart** [comment]
需要本地安装并开启redis

**Comment by wind13** [comment]
不是说开发模式已经去掉了 redis 吗？

**Comment by loaden** [comment]
现在无论是本地开发还是生产环境，都需要redis开启。
建议直接去掉redis的启用配置，以免给用户带来疑惑。

**Comment by loaden** [comment]
// redis配置
    openRedis: true, // 测试或生产环境必须开启
原来已经改了。

**Comment by loaden** [comment]
建议问题解决后的issue及时关闭。不然太多open的issue会让用户误以为bug太多。
