### ISSUE TITLE
npm run dev 报错 - node 版本 10.9.0

### ISSUE THREAD

**Issue by CharlesLiuyx** [doramart/DoraCMS#166]
报错内容

```
> doracms@2.1.0 dev /media/yaoxingliu/Project/FuDe/DoraCMS
> concurrently "npm run devNodeServer" "gulp"

[0] 
[0] > doracms@2.1.0 devNodeServer /media/yaoxingliu/Project/FuDe/DoraCMS
[0] > cross-env NODE_ENV=development MICRO_CACHE=true node ./server
[0] 
[1] gulp[29433]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
[1]  1: 0x8c02c0 node::Abort() [gulp]
[1]  2: 0x8c0395  [gulp]
[1]  3: 0x8f2b77 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
[1]  4: 0xb5859b  [gulp]
[1]  5: 0xb5a532 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
[1]  6: 0x26140b75c01d 
[1] Aborted (core dumped)
[1] gulp exited with code 134
[0] node[29451]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
[0]  1: 0x8c02c0 node::Abort() [node]
[0]  2: 0x8c0395  [node]
[0]  3: 0x8f2b77 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [node]
[0]  4: 0xb5859b  [node]
[0]  5: 0xb5a532 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
[0]  6: 0x37aad53dc01d 
[0] npm run devNodeServer exited with code 0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doracms@2.1.0 dev: `concurrently "npm run devNodeServer" "gulp"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doracms@2.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by CharlesLiuyx** [comment]
尝试 `nvm use 8.1.4` 转换 node 版本后依旧失败，环境 `Ubuntu 16.04`

报错内容
```
> doracms@2.1.0 dev /media/yaoxingliu/Project/FuDe/DoraCMS
> concurrently "npm run devNodeServer" "gulp"

[0] 
[0] > doracms@2.1.0 devNodeServer /media/yaoxingliu/Project/FuDe/DoraCMS
[0] > cross-env NODE_ENV=development MICRO_CACHE=true node ./server
[0] 
[1] /media/yaoxingliu/Project/FuDe/DoraCMS/node_modules/node-sass/lib/binding.js:15
[1]       throw new Error(errors.missingBinary());
[1]       ^
[1] 
[1] Error: Missing binding /media/yaoxingliu/Project/FuDe/DoraCMS/node_modules/node-sass/vendor/linux-x64-57/binding.node
[1] Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
[1] 
[1] Found bindings for the following environments:
[1]   - Linux 64-bit with Unsupported runtime (64)
[1] 
[1] This usually happens because your environment has changed since running `npm install`.
[1] Run `npm rebuild node-sass --force` to build the binding for your current environment.
[1]     at module.exports (/media/yaoxingliu/Project/FuDe/DoraCMS/node_modules/node-sass/lib/binding.js:15:13)
[1]     at Object.<anonymous> (/media/yaoxingliu/Project/FuDe/DoraCMS/node_modules/node-sass/lib/index.js:14:35)
[1]     at Module._compile (module.js:569:30)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:503:32)
[1]     at tryModuleLoad (module.js:466:12)
[1]     at Function.Module._load (module.js:458:3)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/media/yaoxingliu/Project/FuDe/DoraCMS/node_modules/gulp-sass/index.js:187:21)
[1] gulp exited with code 1
[0] Redis状态开关： true
[0] server started at localhost:8080
[0] events.js:182
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[0]     at Object.exports._errnoException (util.js:1022:11)
[0]     at exports._exceptionWithHostPort (util.js:1045:20)
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! doracms@2.1.0 devNodeServer: `cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the doracms@2.1.0 devNodeServer script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0] npm run devNodeServer exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doracms@2.1.0 dev: `concurrently "npm run devNodeServer" "gulp"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doracms@2.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by CharlesLiuyx** [comment]
尝试 `nvm use 8.1.4` `npm rebuild npm-sass --force` 后报错变化
```
> doracms@2.1.0 dev /media/yaoxingliu/Project/FuDe/DoraCMS
> concurrently "npm run devNodeServer" "gulp"

[0] 
[0] > doracms@2.1.0 devNodeServer /media/yaoxingliu/Project/FuDe/DoraCMS
[0] > cross-env NODE_ENV=development MICRO_CACHE=true node ./server
[0] 
[1] [14:05:39] Using gulpfile /media/yaoxingliu/Project/FuDe/DoraCMS/gulpfile.js
[1] [14:05:39] Starting 'default1'...
[1] [14:05:39] Finished 'default1' after 6.66 ms
[1] [14:05:39] Starting 'default2'...
[1] [14:05:39] Finished 'default2' after 1.07 ms
[1] [14:05:39] Starting 'default'...
[1] [14:05:39] Finished 'default' after 671 μs
[0] Redis状态开关： true
[0] server started at localhost:8080
[0] events.js:182
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[0]     at Object.exports._errnoException (util.js:1022:11)
[0]     at exports._exceptionWithHostPort (util.js:1045:20)
[0]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! doracms@2.1.0 devNodeServer: `cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the doracms@2.1.0 devNodeServer script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[0] npm run devNodeServer exited with code 1
```

**Comment by doramart** [comment]
nodejs 10.0 还未兼容到，目前建议使用8以内的版本

**Comment by doramart** [comment]
重新看了下，你需要安装redis

**Comment by loaden** [comment]
10是下一个长期支持版本，建议有空时升级node版本。我目前用9.11.2版本一切正常。
