### ISSUE TITLE
node 启动时报错

### ISSUE THREAD

**Issue by yaochangjun** [doramart/DoraCMS#21]
npm ERR! Failed at the doracms@1.0.9 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the doracms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls doracms
npm ERR! There is likely additional logging output above.

node 版本： v4.2.2
npm 版本 ： 3.3.12

**Comment by chinakids** [comment]
npm install 了么

**Comment by yaochangjun** [comment]
运行了

**Comment by doramart** [comment]
使用  npm start 运行

**Comment by yaochangjun** [comment]
XXXMacBook-Pro:DoraCMS-1.1.0 XXX$ npm start

> doracms@1.0.9 start /Users/XXX/Documents/project/DoraCMS-1.1.0
> node ./bin/www

Port 81 requires elevated privileges

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! doracms@1.0.9 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doracms@1.0.9 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the doracms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls doracms
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yaochangjun/Documents/project/DoraCMS-1.1.0/npm-debug.log

这些就是在运行 npm start时报的错，无法正常启动

**Comment by doramart** [comment]
mac上我确实还没装过，看起来像是依赖问题，可以尝试吧node_modules下所有的依赖删掉再重新npm install

**Comment by yaochangjun** [comment]
能运行了，把端口改掉就好了，估计是权限的问题

**Comment by doramart** [comment]
嗯 那就好！

**Comment by Shany100** [comment]
我尝试在 centos 也没跑不起来，改了端口也不行。报错同上。

**Comment by Shany100** [comment]
```
11 silly lifecycle doracms@1.1.1~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle doracms@1.1.1~start: Returned: code: 1  signal: null
13 info lifecycle doracms@1.1.1~start: Failed to exec start script
14 verbose stack Error: doracms@1.1.1 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v4.4.2/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.4.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid doracms@1.1.1
16 verbose cwd /data/devworkspace/DoraCMS
17 error Linux 2.6.32-358.el6.x86_64
18 error argv "/root/.nvm/versions/node/v4.4.2/bin/node" "/root/.nvm/versions/node/v4.4.2/bin/npm" "start"
19 error node v4.4.2
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error doracms@1.1.1 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the doracms@1.1.1 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the doracms package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs doracms
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls doracms
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by doramart** [comment]
使用npm start 启动服务

**Comment by zhoulijie** [comment]
```
> node ./bin/www

(node:8344) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent versi
on.
_http_outgoing.js:443
    throw new TypeError('First argument must be a string or Buffer');
    ^

TypeError: First argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:443:11)
    at ServerResponse.write (D:\www\201607\DoraCMS\node_modules\compression\index.js:88:18)
    at writetop (D:\www\201607\DoraCMS\node_modules\express-session\index.js:292:22)
    at ServerResponse.end (D:\www\201607\DoraCMS\node_modules\express-session\index.js:328:16)
    at D:\www\201607\DoraCMS\models\ContentTemplate.js:44:21
    at D:\www\201607\DoraCMS\node_modules\mongoose\lib\query.js:2177:21
    at D:\www\201607\DoraCMS\node_modules\kareem\index.js:207:48
    at D:\www\201607\DoraCMS\node_modules\kareem\index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
安装时碰到了这个问题，有遇到过吗？

**Comment by ycjcl868** [comment]
![image](https://cloud.githubusercontent.com/assets/13595509/18084909/8478095e-6edb-11e6-99f3-c230fffefe33.png)
 CentOS 7部署失败

**Comment by doramart** [comment]
起服务了吗，没看见报错

**Comment by ycjcl868** [comment]
npm install时模块安装不了，同样的node和npm版本，在macos下就可以，centos下就不行

**Comment by doramart** [comment]
是不是服务器有墙

**Comment by doramart** [comment]
请升级最新的DoraCMS
