### ISSUE TITLE
tag2.1.6 部署到服务器上  /admin/dashboard 页面.js资源报错 指向127.0.0.1 大佬怎么解决呀

### ISSUE THREAD

**Issue by Yinengmr** [doramart/DoraCMS#233]
```text
system.min.js:4 GET http://127.0.0.1:8080/static/navbar/js/app.js net::ERR_CONNECTION_REFUSED
(anonymous) @ system.min.js:4
h.instantiate @ system.min.js:4
h.instantiate @ system.min.js:4
t.instantiate @ named-register.min.js:1
(anonymous) @ system.min.js:4
Promise.then (async)
t @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
h.import @ system.min.js:4
e.import @ system.min.js:4
t.import @ use-default.min.js:1
singleSpa.registerApplication.eventBus.eventBus @ dashboard:123
(anonymous) @ load.js:18
Promise.then (async)
(anonymous) @ load.js:17
Promise.then (async)
tt @ load.js:8
(anonymous) @ reroute.js:40
Promise.then (async)
Ct @ reroute.js:39
Tt @ apps.js:73
(anonymous) @ dashboard:121
Promise.then (async)
(anonymous) @ dashboard:103
(anonymous) @ dashboard:150
system.min.js:4 GET http://127.0.0.1:8080/static/dashboard/js/app.js net::ERR_CONNECTION_REFUSED
(anonymous) @ system.min.js:4
h.instantiate @ system.min.js:4
h.instantiate @ system.min.js:4
t.instantiate @ named-register.min.js:1
(anonymous) @ system.min.js:4
Promise.then (async)
t @ system.min.js:4
(anonymous) @ system.min.js:4
Promise.then (async)
h.import @ system.min.js:4
e.import @ system.min.js:4
t.import @ use-default.min.js:1
(anonymous) @ dashboard:135
(anonymous) @ load.js:18
Promise.then (async)
(anonymous) @ load.js:17
Promise.then (async)
tt @ load.js:8
(anonymous) @ reroute.js:40
Promise.then (async)
Ct @ reroute.js:39
Tt @ apps.js:73
(anonymous) @ dashboard:121
Promise.then (async)
(anonymous) @ dashboard:103
(anonymous) @ dashboard:150
app-errors.js:9 Uncaught navbar: Application 'navbar' died in status LOADING_SOURCE_CODE: Error loading http://127.0.0.1:8080/static/navbar/js/app.js
    at HTMLScriptElement.<anonymous> (http://dfstyle.top/static/plugins/systemjs/4.1.0/system.min.js:4:4496)
(anonymous) @ system.min.js:4
setTimeout (async)
s @ app-errors.js:9
(anonymous) @ load.js:66
Promise.catch (async)
(anonymous) @ load.js:65
Promise.then (async)
tt @ load.js:8
(anonymous) @ reroute.js:40
Promise.then (async)
Ct @ reroute.js:39
Tt @ apps.js:73
(anonymous) @ dashboard:121
Promise.then (async)
(anonymous) @ dashboard:103
(anonymous) @ dashboard:150
app-errors.js:9 Uncaught dashboard: Application 'dashboard' died in status LOADING_SOURCE_CODE: Error loading http://127.0.0.1:8080/static/dashboard/js/app.js
    at HTMLScriptElement.<anonymous> (http://dfstyle.top/static/plugins/systemjs/4.1.0/system.min.js:4:4496)
(anonymous) @ system.min.js:4
setTimeout (async)
s @ app-errors.js:9
(anonymous) @ load.js:66
Promise.catch (async)
(anonymous) @ load.js:65
Promise.then (async)
tt @ load.js:8
(anonymous) @ reroute.js:40
Promise.then (async)
Ct @ reroute.js:39
Tt @ apps.js:73
(anonymous) @ dashboard:121
Promise.then (async)
(anonymous) @ dashboard:103
(anonymous) @ dashboard:150
dashboard:1 Unchecked runtime.lastError: The message port closed before a response was received.
The resource http://dfstyle.top/static/plugins/element-ui/2.11.1/index.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by doramart** [comment]
请在 config/config.prod.js 中配置 `server_path`  `server_api` 为你服务器的真实信息

**Comment by aLLeENSmith** [comment]
2.1.7 同样的问题
部署参考了
https://www.bookstack.cn/read/doracms-2.1.7/81ed5d8d9e9f0fe8.md

server_path
server_api
都配置了

![image](https://user-images.githubusercontent.com/31880062/97823575-66f71980-1cf4-11eb-97c8-c52d71591d68.png)
![image](https://user-images.githubusercontent.com/31880062/97823595-7a09e980-1cf4-11eb-937c-f433fbde9709.png)
