### ISSUE TITLE
启动时遇到的问题

### ISSUE THREAD

**Issue by zhoulijie** [doramart/DoraCMS#40]
安装时没什么问题。
`npm start` 后，访问 `http://127.0.0.1:81/admin/manage/adminUsersList ` 就报这个错。求解

```
D:\www\201607\DoraCMS>npm start

> doracms@1.1.1 start D:\www\201607\DoraCMS
> node ./bin/www

GET /admin/manage/adminUsersList 302 20.785 ms - 56
GET /admin 200 22.040 ms - -
GET /plugins/font-awesome/css/font-awesome.min.css 200 17.006 ms - -
GET /stylesheets/backstage/css/AdminLTE.min.css 200 20.214 ms - -
GET /plugins/bootstrap/css/bootstrap.min.css 200 27.149 ms - -
GET /admin/vnum?1467697371000 200 14.261 ms - -
GET /javascripts/angular.min.js 200 34.640 ms - -
GET /javascripts/bootstrap.min.js 200 11.549 ms - -
GET /javascripts/jQuery-2.1.3.min.js 200 16.417 ms - -
{ [Error: Not Found] status: 404 }
_http_outgoing.js:447
    throw new TypeError('first argument must be a string or Buffer');
    ^

TypeError: first argument must be a string or Buffer
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:447:11)
    at ServerResponse.write (D:\www\201607\DoraCMS\node_modules\compression\index.js:88:18)
    at writetop (D:\www\201607\DoraCMS\node_modules\express-session\index.js:292:22)
    at ServerResponse.end (D:\www\201607\DoraCMS\node_modules\express-session\index.js:328:16)
    at D:\www\201607\DoraCMS\models\ContentTemplate.js:44:21
    at D:\www\201607\DoraCMS\node_modules\mongoose\lib\query.js:2177:21
    at D:\www\201607\DoraCMS\node_modules\mongoose\node_modules\kareem\index.js:207:48
    at D:\www\201607\DoraCMS\node_modules\mongoose\node_modules\kareem\index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

```

**Comment by doramart** [comment]
at D:\www\201607\DoraCMS\models\ContentTemplate.js:44:21
这里面是不是改啥东西了？

**Comment by zhoulijie** [comment]
@doramart 搞定了，我在配置mongoose里面的远程服务器的时候出的问题。抱歉！
