### ISSUE TITLE
npm run dev的时候报错，求助！

### ISSUE THREAD

**Issue by f39516046** [doramart/DoraCMS#64]
按照流程操作以后
npm run dev的时候报错，求助！
D:\temp\DoraCMS\server\lib\controller\adminUser.js:52
    async getUserSession(req, res, next){
          ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\temp\DoraCMS\server\lib\controller\index.js:1:83)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by doramart** [comment]
升级nodejs到最新版本（8.0及以上）试试
