### ISSUE TITLE
npm  run dev报错

### ISSUE THREAD

**Issue by galary** [doramart/DoraCMS#70]
**错误信息如下**
 node ./build/copy

E:\DoraCMS\server\lib\controller\adminUser.js:54
    async getUserSession(req, res, next) {
          ^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\DoraCMS\server\lib\controller\index.js:1:83)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doracms@2.0.0-beta dev: `npm run static && cross-env NODE_ENV=development MICRO_CACHE=true node ./server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the doracms@2.0.0-beta dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-10-12T03_18_14_698Z-debug.log

**Comment by doramart** [comment]
请把nodejs 升级到8.0以上

**Comment by galary** [comment]
这个权限怎么设置啊   我在本地已经跑了起来，但是配置每个模块都显示没有权限。

**Comment by doramart** [comment]
使用 账号：doramart / 密码：123456 登录

**Comment by galary** [comment]
已经好了，谢谢。

**Comment by galary** [comment]
![image](https://user-images.githubusercontent.com/17908869/31651832-b7541e94-b34f-11e7-8f6d-43840b5b98ab.png)
这些warnings可以不让他显示么

**Comment by doramart** [comment]
生产环境应该是不会显示的

**Comment by simonwoo** [comment]
@galary 全局替换scope=为slot-scope=，就不会出现了

**Comment by doramart** [comment]
恩，vue 版本升级问题，最新的doracms已经修复该问题

**Comment by tbfungeek** [comment]
@galary @doramart 请问这个问题是怎么解决的我也遇到了这个问题：
nodejs 版本 v8.3.0
mongodb 版本 v3.4.7

**Comment by doramart** [comment]
用最新版本（2.0.5）不会有这个问题了
