### ISSUE TITLE
mongodb启用用户名和密码授权访问不能启动

### ISSUE THREAD

**Issue by penweizgx** [doramart/DoraCMS#77]
`(node:26370) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
server started at localhost:3030
(node:26370) DeprecationWarning: `ensureIndex()` is deprecated in Mongoose >= 4.12.0, use `createIndex()` instead
连接数据成功
Unhandled rejection MongoError: not authorized on doracms2 to execute command { listIndexes: "sessions", cursor: {} }
    at Function.MongoError.create (/alidata/www/DoraCMS/node_modules/.2.1.17@mongodb-core/lib/error.js:31:11)
    at queryCallback (/alidata/www/DoraCMS/node_modules/.2.1.17@mongodb-core/lib/cursor.js:212:36)
    at /alidata/www/DoraCMS/node_modules/.2.1.17@mongodb-core/lib/connection/pool.js:469:18
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/alidata/www/DoraCMS/node_modules/.3.5.1@bluebird/js/release/debuggability.js:400:19)
    at Collection.ret [as ensureIndexAsync] (eval at makeNodePromisifiedEval (/alidata/www/DoraCMS/node_modules/.3.5.1@bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
    at MongoStore.setAutoRemoveAsync (/alidata/www/DoraCMS/node_modules/.1.3.2@connect-mongo/src/index.js:129:40)
    at MongoStore.handleNewConnectionAsync (/alidata/www/DoraCMS/node_modules/.1.3.2@connect-mongo/src/index.js:121:18)
    at newConnectionCallback (/alidata/www/DoraCMS/node_modules/.1.3.2@connect-mongo/src/index.js:79:26)
    at connectCallback (/alidata/www/DoraCMS/node_modules/.2.2.33@mongodb/lib/mongo_client.js:515:5)
    at /alidata/www/DoraCMS/node_modules/.2.2.33@mongodb/lib/mongo_client.js:430:11
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

(node:26370) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: not authorized on doracms2 to execute command { insert: "system.indexes", documents: [ { ns: "doracms2.users", key: { _id: 1 }, name: "_id_1", unique: true, background: true } ], ordered: true, writeConcern: { w: 1 } }`

本地通过shell控制台是可以正常访问数据库的
![image](https://user-images.githubusercontent.com/6983487/31716217-65c18e3c-b439-11e7-99d5-b385694acb6e.png)

**Comment by doramart** [comment]
环境变量设置问题，请将 NODE_ENV=production
